-- CreateTable
CREATE TABLE "Tender" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'OPEN',
    "customerName" TEXT,
    "customerEmail" TEXT,
    "tow_vehicle" TEXT,
    "type" TEXT,
    "length" TEXT,
    "frame" TEXT,
    "solar" TEXT,
    "batteries" TEXT,
    "inverter" TEXT,
    "water_tanks" TEXT,
    "external_shower" TEXT,
    "toilet" TEXT,
    "fridge_size" TEXT,
    "fridge_type" TEXT,
    "appliances" TEXT,
    "ac" TEXT,
    "diesel_heater" TEXT,
    "bed" TEXT,
    "kids_beds" TEXT,
    "fixtures" TEXT,
    "outdoor_kitchen" TEXT,
    "electric_awning" TEXT,
    "auto_level" TEXT,
    "final_comments" TEXT,
    "custom_notes" TEXT
);
