export const CARAVAN_MAKES = [
    "Adventura Caravans",
    "Alan Grahams Caravans & RVs",
    "Alpine Caravans",
    "Apache Caravans",
    "Atlantic Caravans",
    "Australian Caravans Direct (ACD)",
    "Australian Motorhomes",
    "Australian Off Road (AOR)",
    "Australis Caravans",
    "Aussie Recreational Vehicles",
    "Avan",
    "Avida",
    "Bayswater Jayco",
    "Bellarine Caravan",
    "Billabong Caravans",
    "Blue Sky Caravans",
    "BRS Offroad",
    "Bruder",
    "Buffalo Caravans",
    "Bushmaster Off-road Caravans",
    "Bushranger Campers",
    "Bushtracker Australia",
    "Camden Caravans",
    "Canterbury Caravans",
    "Canyon Caravans",
    "Caravan City Sales",
    "Caravan Court",
    "Carrera Caravans",
    "Central Coast Crusader",
    "Concept Caravans",
    "Condor Caravans",
    "Coromal Caravans",
    "Coronet RV",
    "Crusader Caravans",
    "CRZR Industries",
    "Cub Campers",
    "Design RV",
    "Domain Caravans",
    "Dreamseeker",
    "East Coast Caravans",
    "Elite Caravans",
    "Elross Caravans",
    "Everest Caravans",
    "Evernew Caravans",
    "Exodus Off Road",
    "Fulchers Caravans",
    "Gateway Motorhomes",
    "Goldstream RV",
    "Grand City Caravans",
    "Great Aussie Caravans",
    "Jayco",
    "JB Caravans",
    "Kedron",
    "Kokoda Caravans",
    "Lanhams Cars & Caravans",
    "Lotus Caravans",
    "Masterpiece Caravans",
    "Network RV",
    "New Age Caravans",
    "New World Caravans & Campers",
    "Nova Caravans",
    "Option RV",
    "Orbit Caravans",
    "Page Bros RV",
    "Paramount Caravans",
    "Parravans Caravan World",
    "Perkins Caravans",
    "Puma RV's Australia",
    "Red Centre Caravans",
    "Retreat Caravans",
    "Robert's RV World",
    "Royal Flair Caravans",
    "Ryan's Caravans",
    "Silver Valley Caravans",
    "Snowy River Caravans",
    "Supreme Caravans",
    "Sydney RV Group",
    "The Caravan Company",
    "Titanium Caravans",
    "Tocumwal Caravans",
    "Vacationer Caravans",
    "Villa Caravans",
    "Wagga Caravan Centre",
    "Willow RV",
    "Wonderland RV",
    "Zone RV",
    "Other"
];

export const CARAVAN_CATEGORIES = [
    "Caravan",
    "Pop Top",
    "Camper Trailer",
    "Motorhome",
    "Campervan",
    "Fifth Wheeler",
    "Slide On"
];

export const STATES = ['NSW', 'VIC', 'QLD', 'WA', 'SA', 'TAS', 'ACT', 'NT'];
